sudo: false
dist: trusty
language: node_js
node_js:
  - '9'

git:
  depth: 1

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  yarn run ci

after_success:
  - cat ./coverage/coverage-final.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage